name: quotly
description: Inspiring quotes for you!
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  loading_animations: ^2.2.0
flutter:
  uses-material-design: true
  fonts:
    - family: PSB
      fonts:
        - asset: assets/fonts/PSB.ttf
    - family: GaramondItalic
      fonts:
        - asset: assets/fonts/GaramondItalic.ttf
